package zemiA;




/**
 * @author gruidae
 * Disharmony を表す列挙型.
 */
public enum Disharmony {
	GOD_CLASS, FEATURE_ENVY, DATA_CLASS, BRAIN_METHOD, BRAIN_CLASS, SIGNIFICANT_DUPLICATION,
	INTENSIVE_COUPLING, DISPERSED_COUPLING, SHOTGUN_SURGERY,
	REFUSED_PARENT_BEQUEST, TRADITION_BREAKER
}
